services:
  coach-app:
    build:
      context: ./coach-app
    container_name: coach-app
    ports:
      - "80:80"
    volumes:
      - ./coach-app:/usr/src/app
      - /usr/src/app/node_modules  # Persist node_modules
    environment:
      - VITE_API_URL=http://localhost:8000  # API URL for your frontend to connect
    networks:
      - coach-network
    depends_on:
      - coach-api 

  coach-api:
    build:
      context: ./coach-api
    container_name: coach-api
    ports:
      - "8000:8000"
    volumes:
      - ./coach-api:/usr/src/app
    depends_on:
      - mysql
    networks:
      - coach-network
    environment:
      - DB_HOST=mysql
      - DB_NAME=super-spin
      - DB_USER=super-spin-admin
      - DB_PASS=naotemsenha

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: naotemsenha
      MYSQL_DATABASE: super-spin
      MYSQL_USER: super-spin-admin
      MYSQL_PASSWORD: naotemsenha
    volumes:
      - ./coach-api/database/coach.sql:/docker-entrypoint-initdb.d/coach.sql
    ports:
      - "3306:3306"
    networks:
      - coach-network

networks:
  coach-network:
    driver: bridge
